[internal]

; Call 1001
exten => 1001,1,Answer()
 same => n,Dial(SIP/1001,20)
 same => n,Hangup()

; Call 1002
exten => 1002,1,Answer()
 same => n,Dial(SIP/1002,20)
 same => n,Hangup()

; Echo test (for checking audio)
exten => 600,1,Answer()
 same => n,Playback(demo-echotest)
 same => n,Echo()
 same => n,Hangup()
